# This file is used to set the compile options for the project.
CXX                         :=  aarch64-linux-gnu-g++

# 3dparty installation directory
OPENCV_INSTALL_DIR          :=  /usr/include/opencv4
RKNN_INSTALL_DIR            :=  ./runtime/Linux/librknn_api
RGA_INCLUDE_DIR             :=  /usr/include/rga
ICEORYX_INCLUDE_DIR         :=  /usr/local/include/iceoryx/v2.95.4
SPDLOG_INCLUDE_DIR          :=  /usr/local/include/spdlog

# Compile options
DEBUG                       :=  0
SHOW_WARNING                :=  0

# Compile applications
APP                         :=  yolo_detector