# This file is used to set the compile options for the project.
CXX                         :=  aarch64-linux-gnu-g++

# Opencv and Tensorrt installation directory
OPENCV_INSTALL_DIR          :=  /usr/include/opencv4
RKNN_INSTALL_DIR            :=  ./runtime/Linux/librknn_api

# Compile options
DEBUG                       :=  0
SHOW_WARNING                :=  0

# Compile applications
APP                         :=  yolo_detector